name: management_game
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: IRANYekan
      fonts:
        - asset: assets/fonts/IRANYekanRegularFaNum.ttf
          weight: 400
        - asset: assets/fonts/IRANYekanMediumFaNum.ttf
          weight: 500
        - asset: assets/fonts/IRANYekanBoldFaNum.ttf
          weight: 700
        - asset: assets/fonts/IRANYekanBlackFaNum.ttf
          weight: 900
